'use strict';
// Biztonságos híd a felület és a főfolyamat között.
const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  native: true,
  platform: 'desktop',
  caps: { mini: true, fullscreen: true, files: true, external: true, health: true, preview: true, exit: false, folders: true, cast: true, share: true, update: true, nightAudio: true, multiview: 4, background: true },
  exit: () => {},
  request: (opts) => ipcRenderer.invoke('http-request', opts),
  requestBytes: (url, headers) => ipcRenderer.invoke('http-request', { url, headers, binary: true }),
  pickFolder: () => ipcRenderer.invoke('pick-folder'),
  themeDirRead: (dir) => ipcRenderer.invoke('theme-dir-read', dir),
  themeDirOpen: (dir) => ipcRenderer.invoke('theme-dir-open', dir),
  scanFolder: (dir) => ipcRenderer.invoke('scan-folder', dir),
  readTextFile: (p) => ipcRenderer.invoke('read-text-file', p),
  sidecarSubs: (videoPath) => ipcRenderer.invoke('sidecar-subs', videoPath),
  sidecarImage: (videoPath) => ipcRenderer.invoke('sidecar-image', videoPath),
  kvGet: (key) => ipcRenderer.invoke('kv-get', key),
  kvSet: (key, value) => ipcRenderer.invoke('kv-set', key, value),
  docGet: (key) => ipcRenderer.invoke('doc-get', key),
  docSet: (key, value) => ipcRenderer.invoke('doc-set', key, value),
  packsScan: () => ipcRenderer.invoke('packs-scan'),
  packsDir: () => ipcRenderer.invoke('packs-dir'),
  fetchText: (url, opts) => ipcRenderer.invoke('fetch-text', url, opts),
  fetchBytes: (url, opts) => ipcRenderer.invoke('fetch-bytes', url, opts),
  setStreamHeaders: (url, headers) => ipcRenderer.invoke('set-stream-headers', url, headers),
  checkStreams: (list) => ipcRenderer.invoke('check-streams', list),
  probe: (item) => ipcRenderer.invoke('probe-one', item),
  preconnect: (url) => ipcRenderer.invoke('preconnect', url),
  cancelCheck: () => ipcRenderer.invoke('cancel-check'),
  onCheckProgress: (cb) => ipcRenderer.on('check-progress', (_e, data) => cb(data)),
  storeLoad: () => ipcRenderer.invoke('store-load'),
  storeSave: (data) => ipcRenderer.invoke('store-save', data),
  clearCache: () => ipcRenderer.invoke('clear-cache'),
  // tartós borítótár (covers.js): a borítókép címe a tárban (adasimg://), méret, ürítés
  coverUrl: (url) => (/^https?:\/\//i.test(String(url || '')) ? 'adasimg://cover/' + Buffer.from(String(url), 'utf8').toString('base64').replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '') : url),
  coverStats: () => ipcRenderer.invoke('covers-stats'),
  coverClear: () => ipcRenderer.invoke('covers-clear'),
  saveFile: (name, text) => ipcRenderer.invoke('save-file', name, text),
  openFile: (filters) => ipcRenderer.invoke('open-file', filters),
  openFiles: (filters) => ipcRenderer.invoke('open-files', filters),
  openExternal: (url) => ipcRenderer.invoke('open-external', url),
  openInPlayer: (items, name) => ipcRenderer.invoke('open-in-player', { items, name }),
  mediaAvailable: () => ipcRenderer.invoke('media-available'),
  mediaStatus: () => ipcRenderer.invoke('media-status'),
  mediaProbe: (url) => ipcRenderer.invoke('media-probe', url),
  mediaStart: (plan) => ipcRenderer.invoke('media-start', plan),
  mediaStop: (id) => ipcRenderer.invoke('media-stop', id),
  recStart: (o) => ipcRenderer.invoke('rec-start', o),
  recStop: (id) => ipcRenderer.invoke('rec-stop', id),
  recList: () => ipcRenderer.invoke('rec-list'),
  recOpen: (p) => ipcRenderer.invoke('rec-open', p),
  recFolder: () => ipcRenderer.invoke('rec-folder'),
  recTrash: (p) => ipcRenderer.invoke('rec-trash', p),
  onRecEnded: (cb) => ipcRenderer.on('rec-ended', (_e, x) => cb(x)),
  recSchedule: (list) => ipcRenderer.invoke('rec-schedule', list),
  onRecDue: (cb) => ipcRenderer.on('rec-due', (_e, id) => cb(id)),
  recTrim: (o) => ipcRenderer.invoke('rec-trim', o),
  recOriginal: (p) => ipcRenderer.invoke('rec-original', p),
  recRestore: (p) => ipcRenderer.invoke('rec-restore', p),
  mediaCover: (url) => ipcRenderer.invoke('media-cover', url),
  onMediaSubs: (cb) => ipcRenderer.on('media-subs', (_e, d) => cb(d)),
  onMediaEnd: (cb) => ipcRenderer.on('media-end', (_e, d) => cb(d)),
  onMediaT0: (cb) => ipcRenderer.on('media-t0', (_e, d) => cb(d)),
  setFullscreen: (on) => ipcRenderer.invoke('set-fullscreen', on),
  onFullscreenChanged: (cb) => ipcRenderer.on('fullscreen-changed', (_e, on) => cb(on)),
  setMini: (on) => ipcRenderer.invoke('set-mini', on),
  setPlaying: (on) => ipcRenderer.invoke('set-playing', on),
  appInfo: () => ipcRenderer.invoke('app-info'),
  notify: (n) => ipcRenderer.invoke('notify', n),
  notifyPermission: () => {},
  onOpenChannel: (cb) => ipcRenderer.on('open-channel', (_e, id) => cb(id)),
  onWentBackground: (cb) => ipcRenderer.on('went-background', () => cb()),
  setBackground: (opts) => ipcRenderer.invoke('set-background', opts),
  castDiscover: () => ipcRenderer.invoke('cast-discover'),
  castPlay: (opts) => ipcRenderer.invoke('cast-play', opts),
  castForget: (id) => ipcRenderer.invoke('cast-forget', id),
  castControl: (action, value) => ipcRenderer.invoke('cast-control', action, value),
  onCastStatus: (cb) => ipcRenderer.on('cast-status', (_e, s) => cb(s)),
  shareStart: (data, id) => ipcRenderer.invoke('share-start', data, id),
  shareStop: () => ipcRenderer.invoke('share-stop'),
  onShareUsed: (cb) => ipcRenderer.on('share-used', (_e, s) => cb(s)),
  onShareLocked: (cb) => ipcRenderer.on('share-locked', () => cb()),
  lanIps: () => ipcRenderer.invoke('lan-ips'),
  lanGet: (urls, timeout) => ipcRenderer.invoke('lan-get', urls, timeout),
  rcStart: (html, pin, key) => ipcRenderer.invoke('rc-start', html, pin, key),
  rcStop: () => ipcRenderer.invoke('rc-stop'),
  rcState: (json) => ipcRenderer.send('rc-state', json),
  setLang: (l) => ipcRenderer.send('set-lang', String(l || '')),
  onRemoteCmd: (cb) => ipcRenderer.on('remote-cmd', (_e, x) => cb(x)),
  updateCheck: (source) => ipcRenderer.invoke('update-check', source),
  updateDownload: (asset) => ipcRenderer.invoke('update-download', asset),
  updateInstall: (file) => ipcRenderer.invoke('update-install', file),
  onUpdateProgress: (cb) => ipcRenderer.on('update-progress', (_e, p) => cb(p)),
});
